import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const app = new URL("./app/", import.meta.url);
const read = (path) => readFile(new URL(path, app), "utf8");

test("imports use real jobs and labeled detail actions", async () => {
  const [page, detail] = await Promise.all([read("app/imports/page.tsx"), read("app/imports/jobs/[jobId]/page.tsx")]);
  assert.match(page, /importJobs\.map/);
  assert.match(page, /Job Details/);
  assert.match(page, /View All Jobs/);
  assert.match(page, /\?entry=imports/);
  assert.match(detail, /entry === "imports"/);
  assert.match(detail, /enteredFromImports/);
  assert.doesNotMatch(page, /visualRows|System status|<button[^>]*>Retry/);
});

test("import setup removes demo category controls and preserves job handoff", async () => {
  const [pdf, website, detail] = await Promise.all([read("app/imports/pdf/pdf-import-client.tsx"), read("app/imports/website/website-import-client.tsx"), read("app/imports/jobs/[jobId]/page.tsx")]);
  assert.doesNotMatch(pdf, /Demo States|Extraction Settings/);
  assert.match(pdf, /router\.push\(`\/app\/imports\/jobs\/\$\{job\.id\}`\)/);
  assert.doesNotMatch(website, /Detected Category Tree|Start Selected Categories|System Ready/);
  assert.doesNotMatch(website, />ACTIVE</);
  assert.match(website, /role="combobox"/);
  assert.match(website, /role="listbox"/);
  assert.match(website, /selectedVendorId/);
  assert.match(website, /entry=website-import/);
  assert.match(detail, /entry === "website-import"/);
});

test("job details offers shared category views and child-job links", async () => {
  const [page, selector, candidates, route, state, shell] = await Promise.all([
    read("app/imports/jobs/[jobId]/page.tsx"),
    read("app/imports/jobs/[jobId]/category-job-selector.tsx"),
    read("app/imports/jobs/[jobId]/candidate-review-table.tsx"),
    read("api/imports/jobs/[jobId]/candidates/route.ts"),
    read("app/imports/jobs/[jobId]/job-detail-state.tsx"),
    read("workspace-shell.tsx"),
  ]);
  assert.match(selector, /Collections/);
  assert.match(selector, /Category Tree/);
  assert.match(selector, /Open child job/);
  assert.match(selector, /aria-checked=\{state\}/);
  assert.match(page, /<details open=\{job\.status === "failed"/);
  assert.match(page, /CandidateReviewTable/);
  assert.match(candidates, /Bulk Edit Category/);
  assert.match(candidates, /Image/);
  assert.match(candidates, /Category/);
  assert.match(candidates, /bulkMode \? <th/);
  assert.doesNotMatch(candidates, /Import Selected|Ignore Selected|Archive Selected|Status filter|>Status</);
  assert.match(route, /categoryEditSchema/);
  assert.match(route, /database\.\$transaction/);
  assert.match(state, /entry === "imports"/);
  assert.match(state, /entry === "website-import"/);
  assert.match(shell, /isImportJobDetailPrototypePage/);
});

test("import jobs use the view-table history contract", async () => {
  const [jobs, detail, loading, error, shell] = await Promise.all([read("app/imports/jobs/page.tsx"), read("app/imports/jobs/[jobId]/page.tsx"), read("app/imports/jobs/loading.tsx"), read("app/imports/jobs/error.tsx"), read("workspace-shell.tsx")]);
  assert.match(jobs, /const pageSize = 10/);
  assert.match(jobs, /vendor: \{ select: \{ name: true \} \}/);
  assert.match(jobs, />Vendor</);
  assert.match(jobs, /Unassigned/);
  assert.match(jobs, /Showing \{rangeStart\}–\{rangeEnd\} of \{totalJobs\} jobs/);
  assert.match(jobs, /entry=jobs/);
  assert.doesNotMatch(jobs, />Events</);
  assert.match(detail, /entry === "jobs"/);
  assert.match(loading, /Import job history loading/);
  assert.match(error, /Import job history error/);
  assert.match(shell, /isImportJobsPrototypePage/);
  assert.match(shell, /isImportsPrototypePage \|\| isImportJobsPrototypePage \|\| isImportJobDetailPrototypePage \? " stitch-imports-shell"/);
});

test("discovery uses the revised searchable editing table", async () => {
  const [page, client, route, loading, error, index, promotion, schema, globals] = await Promise.all([read("app/discovery/page.tsx"), read("app/discovery/discovery-overview-client.tsx"), read("api/discovery-items/route.ts"), read("app/discovery/loading.tsx"), read("app/discovery/error.tsx"), readFile(new URL("../lib/discovery-index.ts", app), "utf8"), readFile(new URL("../../packages/shared/src/discovery.ts", import.meta.url), "utf8"), readFile(new URL("../../prisma/schema.prisma", import.meta.url), "utf8"), readFile(new URL("globals.css", app), "utf8")]);
  assert.match(index, /candidateItem\.findMany/);
  assert.match(index, /catalogItem\.findMany/);
  assert.match(page, /loadDiscoveryItems\(context\.workspaceId, 20\)/);
  assert.match(page, /countDiscoveryItems/);
  for (const label of ["Vendor", "Vendor Price", "Items per page", "Product Details", "Save"]) assert.match(client, new RegExp(label));
  assert.doesNotMatch(client, /Discovery Session:|Confidence|>Preview<|Save & Resolve|Reference:/);
  assert.doesNotMatch(client, /Create Catalog|Import Selected|Add to Catalog|>Ignore<|>Archive</);
  assert.match(client, />Type<\/th><th[^>]*>Category<\/th>/);
  assert.doesNotMatch(client, />Source<\/th>|>Status<\/th>/);
  assert.doesNotMatch(client, /<Filter label="Source Type"|<Filter label="Status"/);
  assert.doesNotMatch(client, />Vendor<\/th>/);
  assert.match(client, /format\(item\.priceCents \/ 100\)/);
  assert.doesNotMatch(client, /format\(item\.vendorPriceCents \/ 100\)/);
  assert.match(client, /aria-label="Search"/);
  assert.match(client, /aria-label="Search"[\s\S]*Reset filters/);
  assert.match(client, /reset: \{ minHeight: 40/);
  assert.match(client, /<span className="sr-only">Items per page<\/span><select[\s\S]*Showing \{totalResults/);
  assert.match(globals, /\.sr-only \{[\s\S]*clip: rect\(0, 0, 0, 0\)/);
  assert.match(client, /fetch\("\/api\/discovery-items"/);
  assert.match(client, /Loading the complete Discovery index/);
  assert.match(client, /conciseText\(item\.name, 58\)/);
  assert.match(client, /conciseText\(item\.sku, 24\)/);
  assert.match(client, /Select visible page|aria-label=\{`Select/);
  assert.match(client, /Delete selected/);
  assert.match(client, /deleteSelected/);
  assert.match(client, /Bulk product type/);
  assert.match(client, /Bulk category/);
  assert.match(client, />Product Type<\/span><input/);
  assert.match(client, />Category<\/span><input/);
  assert.match(client, /bulk-product-type-options/);
  assert.match(client, /bulkItemTypeValid/);
  assert.match(client, /Apply changes/);
  assert.match(client, /applyBulkChanges/);
  assert.match(client, /<\/section>\s*<section aria-label="Bulk actions"[\s\S]*<section style=\{styles\.tableCard\}>/);
  assert.match(client, /Delete \$\{item\.name\}\? This action cannot be undone\./);
  assert.match(client, /method: "DELETE"/);
  assert.match(client, />Vendor Price<input required name="price"/);
  assert.match(client, />Unit Price<input name="vendorPrice"/);
  assert.match(client, />Inventory Quantity<input required name="inventoryQuantity" type="number" min="0" step="1"/);
  assert.doesNotMatch(client, />Cancel</);
  assert.match(loading, /Discovery results loading/);
  assert.match(error, /Discovery results error/);
  assert.match(route, /promoteCandidates/);
  assert.match(route, /vendorPriceCents/);
  assert.match(route, /export async function DELETE/);
  assert.match(route, /export async function GET/);
  assert.match(route, /catalogItem\.deleteMany/);
  assert.match(route, /candidateItem\.deleteMany/);
  assert.match(route, /discovery_selection_invalid/);
  assert.match(route, /database\.\$transaction/);
  assert.match(route, /action: z\.literal\("bulk-edit"\)/);
  assert.match(route, /itemType: z\.enum/);
  assert.match(route, /category: z\.string\(\)\.trim\(\)\.min\(1\)/);
  assert.match(route, /inventoryQuantity: z\.number\(\)\.int\(\)\.nonnegative\(\)/);
  assert.match(promotion, /inventoryQuantity/);
  assert.match(schema, /inventoryQuantity Int @default\(0\)/);
});

test("catalog routes use collection persistence and member operations", async () => {
  const [list, route, form, details, detailPage, memberRoute, loading, error, newLoading, newError, detailLoading, detailError, schema] = await Promise.all([read("app/catalog/catalog-client.tsx"), read("api/catalogs/route.ts"), read("app/catalog/new/new-catalog-item-client.tsx"), read("app/catalog/[itemId]/catalog-details-client.tsx"), read("app/catalog/[itemId]/page.tsx"), read("api/catalogs/[catalogId]/members/route.ts"), read("app/catalog/loading.tsx"), read("app/catalog/error.tsx"), read("app/catalog/new/loading.tsx"), read("app/catalog/new/error.tsx"), read("app/catalog/[itemId]/loading.tsx"), read("app/catalog/[itemId]/error.tsx"), readFile(new URL("../../prisma/schema.prisma", import.meta.url), "utf8")]);
  assert.match(list, /View Details/);
  assert.doesNotMatch(list, /POPULATED|LOADING|EMPTY|ERROR/);
  assert.match(list, /Catalog search and filters/);
  assert.match(list, />Search<\/span><input/);
  assert.match(list, />Category Type<\/span><select/);
  assert.match(list, /Reset filters/);
  assert.match(list, /Select visible catalogs/);
  assert.match(list, /Bulk actions/);
  assert.match(list, /Bulk category type/);
  assert.match(list, /Apply changes/);
  assert.match(list, /Delete selected/);
  assert.match(route, /export async function PATCH/);
  assert.match(route, /export async function DELETE/);
  assert.match(route, /catalog_selection_invalid/);
  assert.match(route, /\$transaction/);
  assert.match(loading, /Catalog list loading/);
  assert.match(error, /Catalog list error/);
  assert.match(form, /Category Type/);
  assert.match(form, /Save Catalog/);
  assert.match(form, /aria-invalid/);
  assert.match(form, /field_errors/);
  assert.doesNotMatch(form, /Pricing|Tax|Save item/);
  assert.match(route, /catalog_name_conflict/);
  assert.match(route, /Use a unique catalog name/);
  assert.match(newLoading, /New catalog form loading/);
  assert.match(newError, /New catalog form error/);
  assert.match(details, /Add from Discovery/);
  assert.match(details, /Catalog member search and filters/);
  assert.match(details, /All Vendors/);
  assert.match(details, /Discovery items available to add/);
  assert.match(details, /Edit Catalog Item/);
  assert.match(details, /Custom Price/);
  assert.match(details, /"Discard"/);
  assert.match(details, /Close catalog item editor/);
  assert.match(details, /underlying Discovery record will be preserved/);
  assert.doesNotMatch(details, />Status<\/th>|>Remove<|\/app\/discovery\?edit=/);
  assert.match(detailPage, /vendor\.findMany/);
  assert.match(detailPage, /archivedAt: null/);
  assert.match(memberRoute, /export async function PATCH/);
  assert.match(memberRoute, /customPriceCents/);
  assert.match(detailLoading, /Catalog details loading/);
  assert.match(detailError, /Catalog details error/);
  assert.match(schema, /model Catalog\s+\{/);
  assert.match(schema, /model CatalogMember\s+\{/);
  assert.match(schema, /customPriceCents Int\?/);
});

test("vendors and workspace settings expose approved real actions", async () => {
  const [vendors, vendorsRoute, vendorLoading, vendorError, detail, detailClient, detailRoute, settings, workspace, route, aiSettings, aiRoute, globalStyles, schema] = await Promise.all([read("app/vendors/vendors-client.tsx"), read("api/vendors/route.ts"), read("app/vendors/loading.tsx"), read("app/vendors/error.tsx"), read("app/vendors/[vendorId]/page.tsx"), read("app/vendors/[vendorId]/vendor-detail-client.tsx"), read("api/vendors/[vendorId]/route.ts"), read("app/settings/page.tsx"), read("app/settings/workspace/workspace-settings-client.tsx"), read("api/workspace-settings/route.ts"), read("app/settings/ai/ai-settings-client.tsx"), read("api/ai-settings/providers/route.ts"), read("globals.css"), readFile(new URL("../../prisma/schema.prisma", import.meta.url), "utf8")]);
  assert.match(vendors, /View Details/);
  assert.match(vendors, /Vendor search and filters/);
  assert.match(vendors, />Search<\/span><input/);
  assert.doesNotMatch(vendors, /Reset filters/);
  assert.match(vendors, /New Vendor/);
  assert.doesNotMatch(vendors, /Vendor status/);
  assert.doesNotMatch(vendors, /Source coverage/);
  assert.doesNotMatch(vendors, /All statuses|All sources/);
  assert.match(vendors, /Vendors per page/);
  assert.match(vendors, /Select visible vendors/);
  assert.match(vendors, /Bulk actions/);
  assert.match(vendors, /Delete selected/);
  assert.match(vendors, /Import-job history will remain/);
  assert.doesNotMatch(vendors, /Bulk vendor status|Apply changes/);
  assert.doesNotMatch(vendors, /Live|Loading|Denied|System Status/);
  assert.match(vendorsRoute, /export async function DELETE/);
  assert.match(vendorsRoute, /vendor_selection_invalid/);
  assert.match(vendorsRoute, /vendor_in_use/);
  assert.match(vendorsRoute, /catalogItem\.count/);
  assert.match(vendorsRoute, /vendor\.deleteMany/);
  assert.doesNotMatch(vendorsRoute, /export async function PATCH/);
  assert.match(vendorsRoute, /getDatabase\(\)\.\$transaction/);
  assert.match(vendorLoading, /Vendor list loading/);
  assert.match(vendorError, /Vendor list error/);
  assert.match(globalStyles, /\.stitch-prototype-content \.vendors-prototype-page \{\s*display: block !important;/);
  assert.doesNotMatch(vendors, /Vendor demo states|System Status/);
  assert.match(detail, /VendorDetailClient/);
  assert.match(detail, /description|contactName|defaultImportMethod|offeringCategories/);
  assert.doesNotMatch(detailClient, />Import<\/Link>/);
  assert.match(detailClient, /Contact Information|Website Details|Products and Services|Recent Import Activity/);
  assert.match(detailClient, /Edit|Save|Cancel/);
  assert.match(detailClient, /Read-only/);
  assert.match(detailClient, /Add offering category/);
  assert.match(detailClient, /mailto:|tel:/);
  assert.match(detailClient, /Only workspace editors can edit vendor details/);
  assert.match(detailClient, /method: "PATCH"/);
  assert.match(detailRoute, /requireEditor/);
  assert.match(detailRoute, /compactUpdateData/);
  assert.match(detailRoute, /offeringCategories/);
  assert.match(detailRoute, /defaultImportMethod: z\.enum\(\["website", "pdf"\]\)/);
  assert.match(schema, /description String\?/);
  assert.match(schema, /contactName String\?/);
  assert.match(schema, /defaultImportMethod String @default\("website"\)/);
  assert.match(schema, /offeringCategories String\[\] @default\(\[\]\)/);
  assert.match(settings, /href="\/app\/settings\/workspace"/);
  assert.match(workspace, /beforeunload|Members and Access|Delete Workspace/);
  assert.match(route, /requireAdmin|workspace\.delete/);
  assert.doesNotMatch(aiSettings, /data-element=\{blueprintActions\.addProvider\.elementId\}|showProviderForm|Health endpoint|name="endpoint"|healthUrl|Provider<select|prototypeProviders|GPT-4o|Claude 3\.5|Documentation|Support/);
  assert.match(aiSettings, /New AI Provider/);
  assert.match(aiSettings, /Provider Name<input required name="provider"/);
  assert.match(aiSettings, /className="ai-provider-type-field">Provider Type<select required name="providerType"/);
  assert.match(aiSettings, /<\/select><\/label>\s*<label>Provider Name.*?<\/label>\s*<label>API Key/s);
  assert.match(aiSettings, /Base API URL<input required name="baseUrl" type="url"/);
  assert.match(aiSettings, /Model ID<input required name="modelId"/);
  assert.match(aiSettings, /API Key\{newProviderType === "ollama" \? " \(optional\)" : ""\}/);
  assert.match(aiSettings, /<section className="ai-add-provider-section" aria-label="New AI Provider">/);
  assert.match(aiSettings, /<section className="ai-add-provider-section" aria-label="Update Provider Credentials">/);
  assert.match(aiSettings, /providers\.filter\(\(provider\) => provider\.enabled\)/);
  assert.doesNotMatch(aiSettings, /routingOptions\.map|disabled=\{!provider\.enabled\}/);
  assert.match(aiSettings, /activeProviders\.map/);
  assert.match(aiSettings, /routeSelections/);
  assert.match(aiSettings, /savedRouteSelections/);
  assert.match(aiSettings, /routingSnapshot/);
  assert.match(aiSettings, /routingDirty/);
  assert.match(aiSettings, /routingCapabilities/);
  assert.doesNotMatch(aiSettings, /View audit log/);
  assert.match(aiSettings, /editingProviderId/);
  assert.match(aiSettings, /editingProvider \? <form className="ai-prototype-card ai-provider-form-card" id="ai-provider-form"/);
  assert.match(aiSettings, /Update Provider/);
  assert.doesNotMatch(aiSettings, /New provider/);
  assert.match(aiSettings, /ai-provider-table-header/);
  assert.match(aiSettings, />Active<\/span><span>Provider<\/span><span>API<\/span><span>Status<\/span><span>Action<\/span>/);
  assert.match(aiSettings, /provider\.lastConnectionStatus === "connected"/);
  assert.match(aiSettings, /ai-connection-status/);
  assert.match(aiSettings, /ai-api-preview/);
  assert.doesNotMatch(aiSettings, /Unavailable/);
  assert.match(aiSettings, /type="checkbox" checked=\{provider\.enabled\}/);
  assert.match(aiSettings, /<span className="sr-only">\{provider\.enabled \? "Active" : "Inactive"\}<\/span>/);
  assert.match(aiSettings, /action: "provider-enabled"/);
  assert.match(aiSettings, /action: "provider-credential"/);
  assert.match(aiSettings, /const formElement = event\.currentTarget;/);
  assert.match(aiSettings, /if \(saved\) \{\s*setEditingProviderId\(null\);\s*formElement\.reset\(\);/);
  assert.doesNotMatch(aiSettings, /event\.currentTarget\.reset/);
  assert.match(aiSettings, /function cancelProviderEdit\(\)/);
  assert.match(aiSettings, /onClick=\{cancelProviderEdit\}>Cancel<\/button>/);
  assert.match(aiSettings, /sortProviders/);
  assert.match(aiSettings, /action: "routing"/);
  assert.match(aiSettings, /setProviders\(sortProviders\(result\.data\.providers\)\)/);
  assert.match(aiSettings, /setRouteSelections\(result\.data\.routes\)/);
  assert.doesNotMatch(aiSettings, /applyProviderResponse|const \[pending, setPending\]/);
  assert.doesNotMatch(aiSettings, /setRouteProviderId\(result\.data\.find/);
  assert.match(aiSettings, /Manual fallback/);
  assert.match(aiSettings, /No active AI providers are configured/);
  assert.match(aiSettings, /Add as many providers as needed; each provider name must be unique\./);
  assert.match(aiSettings, /<colgroup>/);
  assert.match(aiSettings, /disabled=\{savingRouting \|\| !routingDirty\}/);
  assert.match(aiSettings, /routingDirty \? "Save routing" : "Routing saved"/);
  assert.doesNotMatch(aiRoute, /provider: z\.enum\(\["openai-compatible", "ollama"\]\)|updateMany\(\{ where: \{ workspaceId: context\.workspaceId \}, data: \{ enabled: false \} \}/);
  assert.match(aiRoute, /provider: z\.string\(\)\.trim\(\)\.min\(1\)\.max\(80\)\.regex/);
  assert.match(aiRoute, /\\p\{L\}\\p\{N\}/);
  assert.match(aiRoute, /replace\(\/\\s\+\/g, " "\)/);
  assert.match(aiSettings, /firstFieldError\(result\.error\?\.field_errors\)/);
  assert.match(aiRoute, /maskCredential/);
  assert.match(aiRoute, /providerCredentialSchema/);
  assert.match(aiRoute, /newProviderCredentialSchema/);
  assert.match(aiRoute, /providerTypeSchema/);
  assert.match(aiRoute, /parseCredentialConfig\(decryptCredential\(currentProvider\.encryptedCredential\)\)/);
  assert.match(aiRoute, /This provider already exists\. Use its Edit button to update the API key\./);
  assert.match(aiRoute, /aIProviderRoute\.upsert/);
  assert.match(schema, /lastConnectionStatus String\?/);
  assert.match(schema, /lastConnectionCheckedAt DateTime\?/);
  assert.match(schema, /model AIProviderRoute/);
});
